-- ==========================================
-- 1. CRÉATION DES TABLES
-- ==========================================

-- Table Patients
CREATE TABLE patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT UNIQUE NOT NULL,
  id_sgh BIGINT UNIQUE,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  date_naissance DATE,
  sexe TEXT CHECK (sexe IN ('M','F')),
  telephone TEXT,
  email TEXT,
  adresse TEXT,
  groupe_sanguin TEXT,
  allergies TEXT,
  antecedents TEXT,
  qr_code TEXT,
  date_creation TIMESTAMPTZ DEFAULT NOW()
);

-- Table Constantes
CREATE TABLE constantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  nip TEXT REFERENCES patients(nip),
  date_mesure TIMESTAMPTZ DEFAULT NOW(),
  tension_systole INT,
  tension_diastole INT,
  pouls INT,
  temperature NUMERIC(4,1),
  saturation_o2 INT,
  frequence_respiratoire INT,
  poids NUMERIC(5,1),
  taille INT,
  douleur_eva INT,
  glycemie NUMERIC(4,2),
  note TEXT,
  saisie_par TEXT
);

-- Table Consultations
CREATE TABLE consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  nip TEXT,
  date_consultation TIMESTAMPTZ DEFAULT NOW(),
  medecin TEXT,
  motif TEXT,
  diagnostic TEXT,
  prescription TEXT,
  prochain_rdv DATE,
  observations TEXT
);

-- Table Utilisateurs (Staff Clinique)
CREATE TABLE staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  role TEXT CHECK (role IN ('admin','medecin','infirmier')),
  actif BOOLEAN DEFAULT true,
  derniere_connexion TIMESTAMPTZ
);

-- Table Alertes
CREATE TABLE alertes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  constante_id BIGINT REFERENCES constantes(id) ON DELETE CASCADE,
  parametre TEXT,
  valeur NUMERIC,
  seuil_min NUMERIC,
  seuil_max NUMERIC,
  unite TEXT,
  message TEXT,
  niveau TEXT CHECK (niveau IN ('warning','danger')),
  traitee BOOLEAN DEFAULT false,
  traitee_par TEXT,
  salle TEXT,
  date_creation TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. INDEX POUR OPTIMISER LA RECHERCHE
-- ==========================================
CREATE INDEX idx_patient_nip ON patients(nip);
CREATE INDEX idx_patient_nom ON patients(nom);
CREATE INDEX idx_constantes_patient ON constantes(patient_id);
CREATE INDEX idx_alertes_non_traitees ON alertes(traitee) WHERE traitee = false;

-- ==========================================
-- 3. INSERTION DES COMPTES DE DÉMO
-- ==========================================
INSERT INTO staff (username, password_hash, nom, prenom, role) VALUES
('admin', 'admin123', 'Administrateur', 'Clinique', 'admin'),
('dr.kone', 'medecin', 'KONE', 'Dr. Awa', 'medecin'),
('inf.diallo', 'infirmier', 'DIALLO', 'Fatoumata', 'infirmier');

-- ==========================================
-- 4. SÉCURITÉ (Row Level Security)
-- ==========================================
-- On active RLS mais on autorise tout le trafic web avec la Publishable Key
-- (Dans un environnement de prod strict, il faudrait lier ça à Supabase Auth)
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE constantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE alertes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Accès public staff" ON patients FOR ALL USING (true);
CREATE POLICY "Accès public staff" ON constantes FOR ALL USING (true);
CREATE POLICY "Accès public staff" ON consultations FOR ALL USING (true);
CREATE POLICY "Accès public staff" ON staff FOR ALL USING (true);
CREATE POLICY "Accès public staff" ON alertes FOR ALL USING (true);
