-- ===========================================================
-- 0. NETTOYAGE (si vous voulez repartir de zéro)
-- ===========================================================
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS archives CASCADE;
DROP TABLE IF EXISTS carnet_digital CASCADE;
DROP TABLE IF EXISTS rapprochements_patients CASCADE;
DROP TABLE IF EXISTS consultations CASCADE;
DROP TABLE IF EXISTS constantes CASCADE;
DROP TABLE IF EXISTS parcours_patient CASCADE;
DROP TABLE IF EXISTS pre_enregistrements CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS staff CASCADE;

-- ===========================================================
-- 1. STAFF (comptes utilisateurs : admin, médecin, infirmier, archiviste, secrétaire)
-- ===========================================================
CREATE TABLE staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  role TEXT CHECK (role IN ('admin','medecin','infirmier','archiviste','secretaire')) NOT NULL,
  actif BOOLEAN DEFAULT true,
  derniere_connexion TIMESTAMPTZ
);

INSERT INTO staff (username, password_hash, nom, prenom, role) VALUES
('admin', 'admin123', 'Administrateur', 'Clinique', 'admin'),
('dr.kone', 'medecin', 'KONE', 'Dr. Awa', 'medecin'),
('dr.toure', 'medecin', 'TOURE', 'Dr. Ibrahim', 'medecin'),
('inf.diallo', 'infirmier', 'DIALLO', 'Fatoumata', 'infirmier'),
('inf.sangare', 'infirmier', 'SANGARE', 'Mariam', 'infirmier'),
('arc.bamba', 'archiviste', 'BAMBA', 'Aïcha', 'archiviste'),
('sec.doumbia', 'secretaire', 'DOUMBIA', 'Kadi', 'secretaire');

-- ===========================================================
-- 2. PRE-ENREGISTREMENTS (ce que la secrétaire saisit AVANT SGH)
-- ===========================================================
CREATE TABLE pre_enregistrements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pre_id TEXT UNIQUE NOT NULL,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  date_naissance DATE,
  sexe TEXT CHECK (sexe IN ('M','F')),
  telephone TEXT,
  adresse TEXT,
  motif TEXT,
  note_accueil TEXT,
  cree_par TEXT,
  date_creation TIMESTAMPTZ DEFAULT NOW(),
  statut TEXT DEFAULT 'en_attente_enregistrement_paiement',
  patient_id BIGINT,
  nip TEXT,
  date_synchro_sgh TIMESTAMPTZ
);

CREATE INDEX idx_pre_statut ON pre_enregistrements(statut);
CREATE INDEX idx_pre_date ON pre_enregistrements(date_creation DESC);

-- ===========================================================
-- 3. PATIENTS (dossier unique officiel après SGH)
-- ===========================================================
CREATE TABLE patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT UNIQUE,
  id_sgh BIGINT UNIQUE,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  date_naissance DATE,
  sexe TEXT CHECK (sexe IN ('M','F')),
  telephone TEXT,
  email TEXT,
  adresse TEXT,
  groupe_sanguin TEXT,
  allergies TEXT,
  antecedents TEXT,
  contact_urgence TEXT,
  assurance TEXT,
  qr_code TEXT,
  date_creation TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_patient_nip ON patients(nip);
CREATE INDEX idx_patient_nom ON patients(nom);

-- ===========================================================
-- 4. PARCOURS PATIENT (suivi du jour, statut clinique)
-- ===========================================================
CREATE TABLE parcours_patient (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  pre_enregistrement_id BIGINT REFERENCES pre_enregistrements(id),
  nip TEXT,
  date_journee DATE DEFAULT CURRENT_DATE,
  statut TEXT NOT NULL DEFAULT 'en_attente_constantes',
  heure_pre_enregistrement TIMESTAMPTZ,
  heure_synchro_sgh TIMESTAMPTZ,
  heure_constantes TIMESTAMPTZ,
  heure_medecin TIMESTAMPTZ,
  heure_fin TIMESTAMPTZ,
  source TEXT DEFAULT 'SGH',
  commentaire TEXT
);

CREATE INDEX idx_parcours_statut ON parcours_patient(statut);
CREATE INDEX idx_parcours_date ON parcours_patient(date_journee DESC);

-- ===========================================================
-- 5. CONSTANTES (saisies infirmier)
-- ===========================================================
CREATE TABLE constantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  parcours_id BIGINT REFERENCES parcours_patient(id) ON DELETE CASCADE,
  nip TEXT,
  date_mesure TIMESTAMPTZ DEFAULT NOW(),
  tension_systole INT,
  tension_diastole INT,
  pouls INT,
  temperature NUMERIC(4,1),
  saturation_o2 INT,
  frequence_respiratoire INT,
  poids NUMERIC(5,1),
  taille INT,
  douleur_eva INT,
  glycemie NUMERIC(4,2),
  note TEXT,
  saisie_par TEXT
);

-- ===========================================================
-- 6. CONSULTATIONS (médecin)
-- ===========================================================
CREATE TABLE consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  parcours_id BIGINT REFERENCES parcours_patient(id) ON DELETE CASCADE,
  nip TEXT,
  date_consultation TIMESTAMPTZ DEFAULT NOW(),
  medecin TEXT,
  motif TEXT,
  diagnostic TEXT,
  prescription TEXT,
  observations TEXT,
  prochain_rdv DATE
);

-- ===========================================================
-- 7. CARNET DIGITAL (santé long-terme du patient)
-- ===========================================================
CREATE TABLE carnet_digital (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  nip TEXT UNIQUE NOT NULL,
  allergies TEXT,
  antecedents TEXT,
  traitements_chroniques TEXT,
  vaccinations TEXT,
  observations_longitudinales TEXT,
  derniere_mise_a_jour TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================================
-- 8. ARCHIVES (documents archiviste)
-- ===========================================================
CREATE TABLE archives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  nip TEXT,
  titre TEXT NOT NULL,
  type_fichier TEXT NOT NULL,
  url_fichier TEXT,
  ajoute_par TEXT,
  date_ajout TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================================
-- 9. RAPPROCHEMENTS (anti-doublon, fusion)
-- ===========================================================
CREATE TABLE rapprochements_patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id BIGINT,
  cible_id BIGINT,
  score_correspondance NUMERIC,
  raison TEXT,
  statut TEXT DEFAULT 'en_attente',
  date_creation TIMESTAMPTZ DEFAULT NOW(),
  valide_par TEXT
);

-- ===========================================================
-- 10. ALERTES (constantes anormales)
-- ===========================================================
CREATE TABLE alertes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
  constante_id BIGINT REFERENCES constantes(id) ON DELETE CASCADE,
  parcours_id BIGINT REFERENCES parcours_patient(id) ON DELETE CASCADE,
  parametre TEXT,
  valeur NUMERIC,
  seuil_min NUMERIC,
  seuil_max NUMERIC,
  unite TEXT,
  message TEXT,
  niveau TEXT CHECK (niveau IN ('warning','danger')),
  traitee BOOLEAN DEFAULT false,
  traitee_par TEXT,
  salle TEXT,
  date_creation TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_alertes_non_traitees ON alertes(traitee) WHERE traitee = false;

-- ===========================================================
-- 11. AUDIT LOGS (traçabilité confidentialité)
-- ===========================================================
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_role TEXT,
  user_name TEXT,
  action TEXT NOT NULL,
  cible_type TEXT,
  cible_id TEXT,
  details TEXT,
  date_action TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================================
-- 12. SÉCURITÉ (Row Level Security permissive pour app interne)
-- ===========================================================
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE pre_enregistrements ENABLE ROW LEVEL SECURITY;
ALTER TABLE parcours_patient ENABLE ROW LEVEL SECURITY;
ALTER TABLE constantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE carnet_digital ENABLE ROW LEVEL SECURITY;
ALTER TABLE archives ENABLE ROW LEVEL SECURITY;
ALTER TABLE alertes ENABLE ROW LEVEL SECURITY;
ALTER TABLE rapprochements_patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Policies : accès complet via la clé anon (clinic app)
CREATE POLICY "staff_all" ON staff FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "patients_all" ON patients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pre_all" ON pre_enregistrements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "parcours_all" ON parcours_patient FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "constantes_all" ON constantes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "consultations_all" ON consultations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "carnet_all" ON carnet_digital FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "archives_all" ON archives FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "alertes_all" ON alertes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "rappro_all" ON rapprochements_patients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "audit_all" ON audit_logs FOR ALL USING (true) WITH CHECK (true);

-- Realtime pour les alertes et parcours (nécessite activation dans Supabase Dashboard > Database > Replication)
ALTER PUBLICATION supabase_realtime ADD TABLE alertes;
ALTER PUBLICATION supabase_realtime ADD TABLE parcours_patient;
ALTER PUBLICATION supabase_realtime ADD TABLE patients;